---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: "^django-pam/"
default_language_version:
  # force all unspecified python hooks to run python3
  python: python3

repos:

  # GENERAL
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-json
      - id: check-xml
      - id: check-yaml
      - id: trailing-whitespace
  - repo: https://git.knut.univention.de/univention/dist/pre-commit-ucs.git
    rev: v1.4.0
    hooks:
      - id: missing-executable-flag-for-python-file
      - id: missing-executable-flag-for-shell-file

  # DEBIAN
  - repo: https://git.knut.univention.de/univention/dist/pre-commit-debian.git
    rev: v1.1.0
    hooks:
      - id: debian-control
      - id: debian-changelog
  # BASH
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.10.0
    hooks:
      - id: shellcheck
        stages: [manual]
        # args: ["--severity=warning"]  # Optionally only show errors and warnings
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.11.0-1
    hooks:
      # Choose one of:
      - id: shfmt         # prebuilt upstream executable
        # - id: shfmt-src     # build from source (requires/installs Go to build)
        # - id: shfmt-docker  # Docker image (requires Docker to run)
        stages: [manual]

  # PYTHON
  - repo: https://git.knut.univention.de/univention/dist/pre-commit-ucr
    rev: '0.1.2'
    hooks:
      - id: ucr-flake8
        additional_dependencies: ["flake8==5.0.4"]
      - id: ucr-ruff
        additional_dependencies: ["ruff==0.11.2"]
      - id: ucr-autopep8
        additional_dependencies: ["autopep8<=2.0.2"]
        stages: [manual]
      - id: ucr-ruff-fix
        additional_dependencies: ["ruff==0.11.2"]
        stages: [manual]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.11.8'
    hooks:
      - id: ruff
      - id: ruff
        alias: "ruff-fix"
        stages: [manual]
        args: ["--fix", "--unsafe-fixes"]
      - id: ruff
        alias: "ruff-statistics"
        stages: [manual]
        args: ["--statistics"]
      - id: ruff
        alias: "ruff-select"
        stages: [manual]
        args: ["--select", "CPY001"]
      - id: ruff-format
        alias: "ruff-format"
        stages: [manual]
      - id: ruff-format
        alias: "ruff-format-check"
        stages: [manual]
        args: ["--check"]
  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        entry: isort -c
      - id: isort
        alias: "isort-fix"
        stages: [manual]
        entry: isort
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.4
    hooks:
      - id: autopep8
        args: ["-d"]
      - id: autopep8
        alias: "autopep8-fix"
        stages: [manual]
        args: ["-i"]

