#!/bin/bash
#
# shalla-list-downloader for paedmllinux / LMZ
# download/update shallalist and trigger the initializization of the databases
#
# Copyright 2010-2017 Univention GmbH
#
# http://www.univention.de/
#
# All rights reserved.
#
# The source code of this program is made available
# under the terms of the GNU Affero General Public License version 3
# (GNU AGPL V3) as published by the Free Software Foundation.
#
# Binary versions of this program provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention and not subject to the GNU AGPL V3.
#
# In the case you use this program under the terms of the GNU AGPL V3,
# the program is provided in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License with the Debian GNU/Linux or Univention distribution in file
# /usr/share/common-licenses/AGPL-3; if not, see
# <http://www.gnu.org/licenses/>.

##
BL_DIR=blacklists
DBHOME=/var/lib/ucs-school-webproxy
URL=http://www.shallalist.de/Downloads/shallalist.tar.gz
BL_PKG=shallalist.tar.gz
#
##
# First things first: we need a logfile:
##

. /usr/share/univention-lib/all.sh
create_logfile_if_missing /var/log/univention/ucs-school-webproxy.log "root:adm" 640

exec 3>>/var/log/univention/ucs-school-webproxy.log
exec 1>&3
echo "---------------------------------------------"
echo "Process started: ($(date))"



##
# If something goes wrong, we need to know about it:
##

FAIL () { # log error message to log file and std-err, then fail
        echo "$@"
        echo "$@" >&2
	#clean up temporary files
    CLEAN
	echo "List download/update interrupted ($(date)): See log files"
	echo "--------------------* * *--------------------"

    exit 1
}
##
# To be able to read from Univention-Configuration-Registry we need this one:
##

eval "$(ucr shell proxy/filter/blacklists)"

# clean up...
CLEAN () {
	rm -rf "${TMP_DIR}"
}

if [ -z "${proxy_filter_blacklists}" ]; then
	# no lists configured, don't download anything
	if [ -e "${DBHOME}/${BL_DIR}" ]; then
		rm -rf "${DBHOME}/${BL_DIR}"
	fi
	exit 0
fi

TMP_DIR=$(mktemp -d)
cd "${TMP_DIR}"

echo "Downloading lists..."
wget -q "${URL}" "${URL}.md5"
if [ $? -ne 0 ]; then
	FAIL "Failed to download the lists: Check the connection and try again"
fi
md5sum -c "${BL_PKG}.md5"
if [ $? -ne 0 ]; then
	FAIL "Failed to verify the checksum: try again"
fi
#Extract and update
tar zxf "${BL_PKG}"

if [ ! -d "${DBHOME}/${BL_DIR}" ]; then
	mkdir "${DBHOME}/${BL_DIR}"
fi
cp -rf BL/* "${DBHOME}/${BL_DIR}"
echo "...OK!"

#echo "Setting lists permissions"
chown -R root:proxy "${DBHOME}/${BL_DIR}"
chmod -R g+rw "${DBHOME}/${BL_DIR}"

#call webproxy to reload
if [[ -n "${proxy_filter_blacklists}" ]]; then
	ucr set proxy/filter/blacklists="${proxy_filter_blacklists}"
fi

#clean up tar.gz and md5 files
CLEAN
echo "Download/update finished ($(date))"
echo "--------------------* * *--------------------"
exit 0
