#!/bin/bash -e
#Copyright (C) 2017 Univention GmbH
#
#http://www.univention.de/
#
#All rights reserved.
#
#The source code of the software contained in this package
#as well as the source package itself are made available
#under the terms of the GNU Affero General Public License version 3
#(GNU AGPL V3) as published by the Free Software Foundation.
#
#Binary versions of this package provided by Univention to you as
#well as other copyrighted, protected or trademarked materials like
#Logos, graphics, fonts, specific documentations and configurations,
#cryptographic keys etc. are subject to a license agreement between
#you and Univention and not subject to the GNU AGPL V3.
#
#In the case you use the software under the terms of the GNU AGPL V3,
#the program is provided in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#GNU Affero General Public License for more details.
#
#You should have received a copy of the GNU Affero General Public
#License with the Debian GNU/Linux or Univention distribution in file
#/usr/share/common-licenses/AGPL-3; if not, see
#<http://www.gnu.org/licenses/>.

#DEBHELPER#

eval $(ucr shell ldap/base)

# Pre-set Guacamole UCR variables
/usr/sbin/univention-config-registry set \
	guacamole/user/dn?"cn=users,${ldap_base}" \
	guacamole/config/base/dn?"cn=groups,${ldap_base}" \
	guacamole/ldap/username/attribute?"uid" \
	guacamole/external/port?"8080"

echo -e "---------------"
echo -e "Please check the following UCR variables for correct values before running the joinscript '99univention_install_guacamole.inst':"
echo -e "\t* guacamole/user/dn"
echo -e "\t* guacamole/config/base/dn"
echo -e "\t* guacamole/ldap/username/attribute"
echo -e "\t* guacamole/external/port"
echo -e "---------------"

. /usr/share/univention-lib/base.sh
call_joinscript 98univention_guacamole_searchuser.inst

exit 0
