usr/lib/univention-uninstall/01univention_register_guacamole_schema-uninstall.uinst
usr/lib/univention-install/99univention_register_guacamole_schema.inst
var/lib/univention-ldap/local-schema/guacConfigGroup.schema
usr/share/pyshared/univention/admin/syntax.d/guacamole_protocol.py
usr/share/guacamole/de.mo
usr/share/guacamole/guacamole.py
usr/share/guacamole/guacamole_16.png
usr/share/guacamole/guacamole_50.png
