#!/bin/bash
#
# shalla-list-downloader
# download/update shallalist and trigger the initializization of the databases
#
# Copyright 2010-2017 Univention GmbH
#
# http://www.univention.de/
#
# All rights reserved.
#
# The source code of this program is made available
# under the terms of the GNU Affero General Public License version 3
# (GNU AGPL V3) as published by the Free Software Foundation.
#
# Binary versions of this program provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention and not subject to the GNU AGPL V3.
#
# In the case you use this program under the terms of the GNU AGPL V3,
# the program is provided in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License with the Debian GNU/Linux or Univention distribution in file
# /usr/share/common-licenses/AGPL-3; if not, see
# <http://www.gnu.org/licenses/>.

##
BL_DIR="blacklists"
DBHOME="/usr/local/share/univention-shalla-list-downloader" # TODO: Link wanted categories into /var/lib/ucs-school-webproxy folder (link, not copy, if possible)
BL_PKG="shallalist.tar.gz"
URL="http://www.shallalist.de/Downloads/${BL_PKG}"

#
. /usr/share/univention-lib/all.sh

#
##
# First things first: we need a logfile:
##

# TODO: Generalize, don't use the webproxy log

#create_logfile_if_missing /var/log/univention/ucs-school-webproxy.log "root:adm" 640

#exec 3>>/var/log/univention/ucs-school-webproxy.log
#exec 1>&3
echo "---------------------------------------------"
echo "Process started: ($(date))"



##
# If something goes wrong, we need to know about it:
##

FAIL () { # log error message to log file and std-err, then fail
        echo "$@"
        echo "$@" >&2
	#clean up temporary files
    CLEAN
	echo "List download/update interrupted ($(date)): See log files"
	echo "--------------------* * *--------------------"

    exit 1
}

# clean up...
CLEAN () {
	rm -rf "${TMP_DIR}"
}

TMP_DIR=$(mktemp -d)
cd "${TMP_DIR}"

echo "Checking for updated lists..."
wget -q "${URL}.md5"
if [ $? -ne 0 ]; then
	FAIL "Failed to download the lists: Check the connection and try again"
fi

cmp --silent "${BL_PKG}.md5" "${DBHOME}/${BL_DIR}/${BL_PKG}.md5"
if [ $? -eq 0 ]; then
	CLEAN
	echo "Nothing changed since the last update"
	echo "Download/update finished ($(date))"
	echo "--------------------* * *--------------------"
	exit 0
fi

echo "Update available. Downloading lists..."
wget -q "${URL}"
if [ $? -ne 0 ]; then
	FAIL "Failed to download the lists: Check the connection and try again"
fi
md5sum -c "${BL_PKG}.md5"
if [ $? -ne 0 ]; then
	FAIL "Failed to verify the checksum: try again"
fi
#Extract and update
tar zxf "${BL_PKG}"

if [ ! -d "${DBHOME}/${BL_DIR}" ]; then
	mkdir -p "${DBHOME}/${BL_DIR}"
fi
cp -rf BL/* "${DBHOME}/${BL_DIR}"
cp -f "${BL_PKG}.md5" "${DBHOME}/${BL_DIR}"
echo "...OK!"

#clean up tar.gz and md5 files
CLEAN
echo "Download/update finished ($(date))"
echo "--------------------* * *--------------------"
exit 0

#########################



# TODO: Generalize, is this needed?
#echo "Setting lists permissions"
#chown -R root:proxy "${DBHOME}/${BL_DIR}"
#chmod -R g+rw "${DBHOME}/${BL_DIR}"

# TODO: Generalize, only reload the webproxy if variable is set
# TODO: Generalize, do the same for the dns blacklist
#call webproxy to reload
#if [[ -n "${proxy_filter_global_blacklists_domains}" ]]; then
#	ucr set proxy/filter/global/blacklists/domains="${proxy_filter_global_blacklists_domains}"
#fi


