#!/bin/bash
#
# shalla-list-relink
# relink shallalist into proxy and/or dns and trigger the initializization of their databases
#
# Copyright 2017 Univention GmbH
#
# http://www.univention.de/
#
# All rights reserved.
#
# The source code of this program is made available
# under the terms of the GNU Affero General Public License version 3
# (GNU AGPL V3) as published by the Free Software Foundation.
#
# Binary versions of this program provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention and not subject to the GNU AGPL V3.
#
# In the case you use this program under the terms of the GNU AGPL V3,
# the program is provided in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License with the Debian GNU/Linux or Univention distribution in file
# /usr/share/common-licenses/AGPL-3; if not, see
# <http://www.gnu.org/licenses/>.

##
BL_DIR="shallalists"
DBHOME="/usr/local/share/univention-shalla-list-downloader" 
PROXYHOME="/var/lib/ucs-school-webproxy"
RELOAD=true
#
. /usr/share/univention-lib/all.sh

case "$1" in
	-u|--ucr)
	RELOAD=false
	shift
	;;
	*)
	shift
	;;
esac

#
##
# First things first: we need a logfile:
##

# TODO: Generalize, don't use the webproxy log

#create_logfile_if_missing /var/log/univention/ucs-school-webproxy.log "root:adm" 640

#exec 3>>/var/log/univention/ucs-school-webproxy.log
#exec 1>&3
#echo "---------------------------------------------"
#echo "Process started: ($(date))"



eval "$(ucr shell proxy/filter/global/blacklists/domains)"
eval "$(ucr shell proxy/filter/global/blacklists/urls)"
if [[ -n "${proxy_filter_global_blacklists_domains}" || -n "${proxy_filter_global_blacklists_urls}"  ]]; then
	# Trigger reload of the webproxy
	if $RELOAD; then
		ucr set proxy/filter/global/blacklists/domains="${proxy_filter_global_blacklists_domains}"
	else
		echo "Resyncing the proxy blacklist"
		# recreate all links
		rm -rf "$PROXYHOME/$BL_DIR"
		ln -s "$DBHOME/$BL_DIR" "$PROXYHOME/$BL_DIR"
	fi

	# TODO: is this needed?
	#echo "Setting lists permissions"
	#chown -R root:proxy "${DBHOME}/${BL_DIR}"
	#chmod -R g+rw "${DBHOME}/${BL_DIR}"
fi

eval "$(ucr shell dns/blacklist/record/domains)"
if [[ -n "${dns_blacklist_record_domains}" ]]; then
	# Trigger reload of the dns server
	if $RELOAD; then
		echo "Resyncing the bind blacklist"
		/usr/share/univention-bind-blacklist/univention-bind-blacklist
	fi
fi

#echo "Resync/Relink finished ($(date))"
#echo "--------------------* * *--------------------"
exit 0
