#!/bin/bash
#
# shalla-list-relink
# relink shallalist into proxy and/or dns and trigger the initializization of their databases
#
# Copyright 2017-2018 Univention GmbH
#
# http://www.univention.de/
#
# All rights reserved.
#
# The source code of this program is made available
# under the terms of the GNU Affero General Public License version 3
# (GNU AGPL V3) as published by the Free Software Foundation.
#
# Binary versions of this program provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention and not subject to the GNU AGPL V3.
#
# In the case you use this program under the terms of the GNU AGPL V3,
# the program is provided in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License with the Debian GNU/Linux or Univention distribution in file
# /usr/share/common-licenses/AGPL-3; if not, see
# <http://www.gnu.org/licenses/>.

##
BL_DIR="shallalists"
DBHOME="/usr/local/share/univention-shalla-list-downloader" 
PROXYHOME="/var/lib/ucs-school-webproxy"
#
. /usr/share/univention-lib/all.sh

create_logfile_if_missing /var/log/univention/shalla-list-downloader.log "root:adm" 640
exec 3>>/var/log/univention/shalla-list-downloader.log
exec 1>&3

echo "Resyncing the proxy blacklist"
# Recursively create the Webproxy directory, as it is no forced dependency anymore
if [ ! -d "$DIRECTORY" ]; then
	mkdir -p "$PROXYHOME"
fi
# Recreate all links, even if the Webproxy isn't installed
rm -rf "$PROXYHOME/$BL_DIR"
ln -s "$DBHOME/$BL_DIR" "$PROXYHOME/$BL_DIR"

if dpkg --get-selections | grep -q "^ucs-school-webproxy[[:space:]]*install$"; then
	# Trigger reload of the webproxy
	# Note: Regeneration has to be triggered with 'proxy/filter/global/blacklists/%s' variable. Else the config file won't get regenerated
	eval "$(ucr shell proxy/filter/global/blacklists/domains)"
	ucr set proxy/filter/global/blacklists/domains="${proxy_filter_global_blacklists_domains}"
fi

eval "$(ucr shell dns/blacklist/record/domains)"
if [[ -n "${dns_blacklist_record_domains}" ]]; then
	# Trigger reload of the dns server
	echo "Resyncing the bind blacklist"
	/usr/share/univention-bind-blacklist/univention-bind-blacklist
fi

exit 0
