#!/bin/sh
#
# Test module and script
#
# Copyright 2010-2015 Univention GmbH
#
# http://www.univention.de/
#
# All rights reserved.
#
# The source code of this program is made available
# under the terms of the GNU Affero General Public License version 3
# (GNU AGPL V3) as published by the Free Software Foundation.
#
# Binary versions of this program provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention and not subject to the GNU AGPL V3.
#
# In the case you use this program under the terms of the GNU AGPL V3,
# the program is provided in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License with the Debian GNU/Linux or Univention distribution in file
# /usr/share/common-licenses/AGPL-3; if not, see
# <http://www.gnu.org/licenses/>.

set -e

alias udm=univention-directory-manager

position="cn=sudo-ldap,cn=univention,$(ucr get ldap/base)"

udm sudo/rule create --position="$position" --set name=rule1 --set description='Beschreibungstext' --append users=Administrator --append users='%Domain Admins' --append hosts=ALL --append command=/bin/echo --append command='!/bin/*sh'
univention-ldapsearch -xLLL cn=rule1

dn=$(udm sudo/rule list --filter name=rule1 | sed -ne 's/^DN: //p')
udm sudo/rule modify --dn "$dn" --append users=foobar --remove users=Administrator
univention-ldapsearch -xLLL cn=rule1

udm sudo/rule create --position="$position" --set name=rule2 --set description='Beschreibungstext' --append users=Administrator --append users='%Domain Admins' --append hosts=ALL --append command=/bin/echo --append command='!/bin/*sh'
univention-ldapsearch -xLLL cn=rule2

udm sudo/rule modify --dn "$dn" --set users=ALL
univention-ldapsearch -xLLL cn=rule1

udm sudo/rule remove --dn "$dn"
udm sudo/rule remove --filter name=rule2

echo "Success."
