#!/bin/bash
# /etc/init.d/libvirt-wakeonlan
#
# Copyright 2015 Univention GmbH
# 
# http://www.univention.de/
# 
# All rights reserved.
# 
# The source code of this program is made available
# under the terms of the GNU Affero General Public License version 3
# (GNU AGPL V3) as published by the Free Software Foundation.
# 
# Binary versions of this program provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention and not subject to the GNU AGPL V3.
# 
# In the case you use this program under the terms of the GNU AGPL V3,
# the program is provided in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public
# License with the Debian GNU/Linux or Univention distribution in file
# /usr/share/common-licenses/AGPL-3; if not, see
# <http://www.gnu.org/licenses/>.

case "$1" in
	start)
		# Checking if libvirt is running
		pidof libvirtd > /dev/null
		if [ "$?" -eq 0 ]; then
			echo -n "Starting libvirt-wakeonlan... "
			. /etc/default/libvirt-wakeonlan
			cd /usr/share/libvirt-wakeonlan/
			exec ./libvirtwol.py $LIBVIRTDWOL_INTERFACE &
			echo "Done."
			exit 0
		else:
			echo "libvirtd is not running!"
			exit 1
		fi
		;;
	stop)
		# Stop the deamon
		echo -n "Stopping libvirt-wakeonlan... "
		pkill -f libvirtwol.py
		pidof libvirtwol.py > /dev/null
		if [ "$?" -eq 1 ]; then
			echo "Done."
			exit 0
		else:
			echo "Failed!"
			exit 1
		fi
		;;
	*)
		# Everything else
		echo "Usage: /etc/init.d/libvirt-wakeonlan {start|stop}"
		exit 1
		;;
esac

exit 0	
