#!/bin/sh

#DEBHELPER#

if [ "$1" = "configure" ]
then
	uinst=/usr/lib/univention-install/50join-ssh-authenticator-uninstall.uinst
	[ -e "$uinst" ] && rm "$uinst"
fi

. /usr/share/univention-lib/base.sh
call_joinscript 50join-ssh-authenticator.inst

echo "configure SSH deamon to use the AuthorizedKeysCommand if not already otherwise set"
ucr set sshd/AuthorizedKeysCommand?/etc/ssh/ldap_auth_keys_search
ucr set sshd/AuthorizedKeysCommandUser?sshAuthenticator

exit 0
