#!/bin/sh
# Config prior to download/install of xxxxx
#
# Copyright (C) 2013-2017 Univention GmbH
#
# http://www.univention.de/
#
# All rights reserved.
#
# The source code of this program is made available
# under the terms of the GNU Affero General Public License version 3
# (GNU AGPL V3) as published by the Free Software Foundation.
#
# Binary versions of this program provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention and not subject to the GNU AGPL V3.
#
# In the case you use this program under the terms of the GNU AGPL V3,
# the program is provided in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License with the Debian GNU/Linux or Univention distribution in file
# /usr/share/common-licenses/AGPL-3; if not, see
# <http://www.gnu.org/licenses/>.

# Source debconf library.
. /usr/share/debconf/confmodule

# Display the license and ask for agreement
db_input high univention-shalla-list-downloader/present-shalla-license-v1 || true
db_input critical univention-shalla-list-downloader/accepted-shalla-license-v1
db_go

# Check their answer.
db_get univention-shalla-list-downloader/accepted-shalla-license-v1
if [ "$RET" = "false" ]; then
    db_input high univention-shalla-list-downloader/error-shalla-license-v1 || true
	db_go
    exit 1
fi
