31univention-usercert.inst usr/lib/univention-install/
admin/hooks.d/SimpleAuthCertificateHook.py usr/lib/python3/dist-packages/univention/admin/hooks.d/
admin/hooks.d/WindowsCertificateHook.py usr/lib/python3/dist-packages/univention/admin/hooks.d/
make-certificates-user.sh usr/share/univention-ssl/
manageusercertificate.py usr/lib/univention-directory-listener/system/
univention-certificate-user usr/sbin/
univention-usercert-expiry usr/share/univention-directory-manager-tools/
