#!/bin/bash
#
# Copyright 2016-2017 Univention GmbH
#
# http://www.univention.de/
#
# All rights reserved.
#
# The source code of this program is made available
# under the terms of the GNU Affero General Public License version 3
# (GNU AGPL V3) as published by the Free Software Foundation.
#
# Binary versions of this program provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention and not subject to the GNU AGPL V3.
#
# In the case you use this program under the terms of the GNU AGPL V3,
# the program is provided in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License with the Debian GNU/Linux or Univention distribution in file
# /usr/share/common-licenses/AGPL-3; if not, see
# <http://www.gnu.org/licenses/>.

. /usr/share/univention-lib/ucr.sh

DIR_LE="/etc/univention/letsencrypt"

if [ ! "$(id -un)" = "root" ] ; then
    echo "ERROR: please restart this script as user 'root'."
    exit 1
fi

# if HTTPS is enforced by apache2, then disable it
if is_ucr_true apache2/force_https; then
    APACHE_FORCE_HTTPS="$(ucr get apache2/force_https)"
    ucr set apache2/force_https=no
    invoke-rc.d apache2 restart
fi

su - letsencrypt -c "/usr/share/univention-letsencrypt/refresh-cert"

openssl x509 -in "$DIR_LE/signed.crt" -text -noout > /dev/null 2>&1
check_cert=$?

if [[ $check_cert -eq 0 ]]; then
    run-parts --verbose "$DIR_LE/post-refresh.d/"
else 
    if [[ $apache2_ssl_certificate == "$DIR_LE/signed.crt" ]]; then
        ucr unset \
            apache2/ssl/certificatechain \
            apache2/ssl/certificate \
            apache2/ssl/key
        invoke-rc.d apache2 restart
    fi

    if [[ $mail_dovecot_ssl_certificate == "$DIR_LE/chained.pem" ]]; then
        ucr unset \
            mail/dovecot/ssl/key \
            mail/dovecot/ssl/certificate \
            mail/dovecot/ssl/cafile
        invoke-rc.d dovecot restart
    fi

    if [[ $mail_postfix_ssl_certificate == "$DIR_LE/signed.crt" ]]; then
        ucr unset \
            mail/postfix/ssl/key\
            mail/postfix/ssl/certificate \
            mail/postfix/ssl/cafile
        invoke-rc.d postfix restart
    fi
fi

#reset force_https config
if [ -n "$APACHE_FORCE_HTTPS" ] ; then
    ucr set apache2/force_https="$APACHE_FORCE_HTTPS"
    invoke-rc.d apache2 restart
fi
