#!/bin/bash -e
#
# Copyright 2016-2017 Univention GmbH
#
# http://www.univention.de/
#
# All rights reserved.
#
# The source code of this program is made available
# under the terms of the GNU Affero General Public License version 3
# (GNU AGPL V3) as published by the Free Software Foundation.
#
# Binary versions of this program provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention and not subject to the GNU AGPL V3.
#
# In the case you use this program under the terms of the GNU AGPL V3,
# the program is provided in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License with the Debian GNU/Linux or Univention distribution in file
# /usr/share/common-licenses/AGPL-3; if not, see
# <http://www.gnu.org/licenses/>.

. /usr/share/univention-lib/ucr.sh

DIR_LE="/etc/univention/letsencrypt"

if [ ! "$(id -un)" = "root" ] ; then
	echo "ERROR: please restart this script as user 'root'."
	exit 1
fi

su - letsencrypt -c "/usr/share/univention-letsencrypt/refresh-cert"

ucr set letsencrypt/status="$(tail -n 1 /var/log/univention/letsencrypt.log)"

openssl x509 -in "$DIR_LE/signed.crt" -text -noout > /dev/null
check_cert=$?

if [[ $check_cert -eq 0 ]]; then
	run-parts --verbose "$DIR_LE/post-refresh.d/"
else 
	ucr unset \
		apache2/ssl/certificatechain \
		apache2/ssl/certificate \
		apache2/ssl/key
	invoke-rc.d apache2 restart
fi
