#!/bin/sh
#Copyright (C) 2016 Univention GmbH
#
#http://www.univention.de/
#
#All rights reserved.
#
#The source code of the software contained in this package
#as well as the source package itself are made available
#under the terms of the GNU Affero General Public License version 3
#(GNU AGPL V3) as published by the Free Software Foundation.
#
#Binary versions of this package provided by Univention to you as
#well as other copyrighted, protected or trademarked materials like
#Logos, graphics, fonts, specific documentations and configurations,
#cryptographic keys etc. are subject to a license agreement between
#you and Univention and not subject to the GNU AGPL V3.
#
#In the case you use the software under the terms of the GNU AGPL V3,
#the program is provided in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#GNU Affero General Public License for more details.
#
#You should have received a copy of the GNU Affero General Public
#License with the Debian GNU/Linux or Univention distribution in file
#/usr/share/common-licenses/AGPL-3; if not, see
#<http://www.gnu.org/licenses/>.

. /usr/share/univention-lib/all.sh

call_joinscript 99univention-samba-config-ransomware.inst

echo "include = /etc/samba/local.config.d/full_audit.global.local.config.conf" >> /etc/samba/local.config.conf

# reload samba
service samba restart

exit 0
