#!/bin/bash
#Copyright (C) 2017 Univention GmbH
#
#http://www.univention.de/
#
#All rights reserved.
#
#The source code of the software contained in this package
#as well as the source package itself are made available
#under the terms of the GNU Affero General Public License version 3
#(GNU AGPL V3) as published by the Free Software Foundation.
#
#Binary versions of this package provided by Univention to you as
#well as other copyrighted, protected or trademarked materials like
#Logos, graphics, fonts, specific documentations and configurations,
#cryptographic keys etc. are subject to a license agreement between
#you and Univention and not subject to the GNU AGPL V3.
#
#In the case you use the software under the terms of the GNU AGPL V3,
#the program is provided in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#GNU Affero General Public License for more details.
#
#You should have received a copy of the GNU Affero General Public
#License with the Debian GNU/Linux or Univention distribution in file
#/usr/share/common-licenses/AGPL-3; if not, see
#<http://www.gnu.org/licenses/>.

eval "$(ucr shell)"

echo -e "Creating new container for Guacamole"
echo -e "---------------"
echo -n "Stopping and removing old Guacamole container... "
/usr/bin/docker stop guacamole > /dev/null
/usr/bin/docker rm guacamole > /dev/null
echo -e "Done!"
echo -n "Creating new Guacamole container... "
/usr/bin/docker run \
    --name guacamole \
    --link guacd:guacd \
    --restart=always \
    -e LDAP_HOSTNAME="${ldap_server_name}" \
    -e LDAP_PORT="${ldap_server_port}" \
    -e LDAP_USER_BASE_DN="${guacamole_user_dn}" \
    -e LDAP_CONFIG_BASE_DN="${guacamole_config_base_dn}" \
    -e LDAP_USERNAME_ATTRIBUTE="${guacamole_ldap_username_attribute}" \
    -e LDAP_SEARCH_BIND_DN="uid=guacamole,cn=users,${ldap_base}" \
    -e LDAP_SEARCH_BIND_PASSWORD="$(cat /etc/guacamole.secret)" \
    -e LDAP_USER_SEARCH_FILTER="${guacamole_ldap_user_searchfilter}" \
    -d -p "${guacamole_external_port}":8080 mjumper/guacamole > /dev/null
/usr/bin/docker cp /usr/share/guacamole/guacamole-auth-ldap-* guacamole:/opt/guacamole/ldap/
/usr/bin/docker cp /usr/share/guacamole/start.sh guacamole:/opt/guacamole/bin
/usr/bin/docker restart guacamole > /dev/null
echo -e "Done!"

exit 0
